AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  myLaunchTemplateVersionNumber:
    Type: String
    Default: "Lohika_course"
  instanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  myKeyPair:
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: 12345
  imageId:
    Description: Amazon EC2 image ID
    Type: String
    Default: ami-7a11e213
Resources:
  myLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        CreditSpecification:
          CpuCredits: Unlimited
        ImageId: !Ref imageId
        InstanceType: !Ref instanceTypeParameter
      UserData:
        Fn::Base64:
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install java-1.8.0-openjdk
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref myKeyPair
      ImageId: !Ref imageId
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 locked down to the load balancer + SSH access"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
  myASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '2'
      MaxSize: '2'
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref myLaunchTemplate
        Version: !Ref myLaunchTemplateVersionNumber
      AvailabilityZone:
        Fn::GetAZs: us-west-2

# aws cloudformation create-stack --stack-name myteststack1 --template-body file://Homework2.yaml --parameters ParameterKey=myLaunchTemplateVersionNumber,ParameterValue=Lohinser ParameterKey=instanceTypeParameter,ParameterValue=t2.micro ParameterKey=myKeyPair,ParameterValue=12345 ParameterKey=imageId,ParameterValue=ami-7a11e213
# aws cloudformation delete-stack --stack-name Lohinser
# aws cloudformation delete-stack --stack-name myteststack1