AWSTemplateFormatVersion: 2010-09-09
Description: "Single EC2 instance"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Network Configuration"
        Parameters:
          - Environment

Parameters:
  Environment:
    Type: String
    Default: "Lohika_course"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailibilityZone: us-west-2
      ImageId: ami-a4c7eb2
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: !Ref Environment

Outputs:
  PublicIp:
    Description: EC2 Instance public IP
    Value: !GetAtt EC2Instance.PublicIp

# aws cloudformation create-stack --stack-name myteststack --template-body file://HomeWork1.yaml --parameters ParameterKey=Environment,ParameterValue=Lohinser
# aws cloudformation delete-stack --stack-name Lohinser
# aws cloudformation delete-stack --stack-name myteststack